name: linter-test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        run: make install
        env:
          CI: true
      - name: linter-t
        run: make lint